//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LjubljanaBus.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LjubljanaBus.Data.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background image by Goran Petrasevic.
        /// </summary>
        public static string aboutPageBgImgBy {
            get {
                return ResourceManager.GetString("aboutPageBgImgBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by Aleš Rosina.
        /// </summary>
        public static string aboutPageTextBy {
            get {
                return ResourceManager.GetString("aboutPageTextBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string aboutPageTitle {
            get {
                return ResourceManager.GetString("aboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow.
        /// </summary>
        public static string allowLabel {
            get {
                return ResourceManager.GetString("allowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancelLabel {
            get {
                return ResourceManager.GetString("cancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available..
        /// </summary>
        public static string listNoData {
            get {
                return ResourceManager.GetString("listNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus station.
        /// </summary>
        public static string mainBusStation {
            get {
                return ResourceManager.GetString("mainBusStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string mainPageAboutBtn {
            get {
                return ResourceManager.GetString("mainPageAboutBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to call moneta pay.
        /// </summary>
        public static string mainPageCallBtn {
            get {
                return ResourceManager.GetString("mainPageCallBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string mainPageFavTab {
            get {
                return ResourceManager.GetString("mainPageFavTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map.
        /// </summary>
        public static string mainPageMapBtn {
            get {
                return ResourceManager.GetString("mainPageMapBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to near me.
        /// </summary>
        public static string mainPageNearMeTab {
            get {
                return ResourceManager.GetString("mainPageNearMeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scheme.
        /// </summary>
        public static string mainPageSchemeBtn {
            get {
                return ResourceManager.GetString("mainPageSchemeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search stations.
        /// </summary>
        public static string mainPageSearchBtn {
            get {
                return ResourceManager.GetString("mainPageSearchBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string mainPageSettingsBtn {
            get {
                return ResourceManager.GetString("mainPageSettingsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aerial view.
        /// </summary>
        public static string mapPageAerialView {
            get {
                return ResourceManager.GetString("mapPageAerialView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to me.
        /// </summary>
        public static string mapPageMyLoc {
            get {
                return ResourceManager.GetString("mapPageMyLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street view.
        /// </summary>
        public static string mapPageStreetView {
            get {
                return ResourceManager.GetString("mapPageStreetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zoom in.
        /// </summary>
        public static string mapPageZoomIn {
            get {
                return ResourceManager.GetString("mapPageZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zoom out.
        /// </summary>
        public static string mapPageZoomOut {
            get {
                return ResourceManager.GetString("mapPageZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking Allow, you will allow this aplication to access location services. You can change this setting later in settings page. You can also view privacy policy later on about page. If you do not allow access to location services, some of fetatures will not be available..
        /// </summary>
        public static string msgAgreeToUseLoc {
            get {
                return ResourceManager.GetString("msgAgreeToUseLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location services must be enabled on your phone..
        /// </summary>
        public static string msgLocServMustBeEnabled {
            get {
                return ResourceManager.GetString("msgLocServMustBeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yaay, no errors were detected!.
        /// </summary>
        public static string msgNoErrorToSend {
            get {
                return ResourceManager.GetString("msgNoErrorToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need internet access to show this data!.
        /// </summary>
        public static string msgNoInternetConn {
            get {
                return ResourceManager.GetString("msgNoInternetConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is using your current location on your explicit request. Your location is never stored on device in any form, except for viewing purposes of nerby bus stations..
        /// </summary>
        public static string msgPrivacyPolicy {
            get {
                return ResourceManager.GetString("msgPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string offLabel {
            get {
                return ResourceManager.GetString("offLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string onLabel {
            get {
                return ResourceManager.GetString("onLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LJUBLJANA BUS SEARCH.
        /// </summary>
        public static string searchPageTitle {
            get {
                return ResourceManager.GetString("searchPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send error report. Thanks!.
        /// </summary>
        public static string settingsErrorReprotBtn {
            get {
                return ResourceManager.GetString("settingsErrorReprotBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow access to your location.
        /// </summary>
        public static string settingsPageLocTitle {
            get {
                return ResourceManager.GetString("settingsPageLocTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For settings to take effect, you must restart app..
        /// </summary>
        public static string settingsPageRestartApp {
            get {
                return ResourceManager.GetString("settingsPageRestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string settingsPageTitle {
            get {
                return ResourceManager.GetString("settingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string stationPageFav {
            get {
                return ResourceManager.GetString("stationPageFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string stationPageRefresh {
            get {
                return ResourceManager.GetString("stationPageRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to due in.
        /// </summary>
        public static string strDueIn {
            get {
                return ResourceManager.GetString("strDueIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string strPrivacyPolicy {
            get {
                return ResourceManager.GetString("strPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tommorow at.
        /// </summary>
        public static string strTommorowAt {
            get {
                return ResourceManager.GetString("strTommorowAt", resourceCulture);
            }
        }
    }
}
